components: 02-elements: cookie-consent: check if there are cookies
ThreeSixtyGiving/360-ds pull request #65
Opened 2022-03-23 16:28 UTC by BibianaC

relates to #63

2022-03-23 16:28 UTC, BibianaC commented
@michaelwood not sure how to test if this works.

2022-03-24 15:01 UTC, michaelwood requested changes
It may be possible to test some of this by pasting it to an application. If we need to test fully we could use the current 360dev server with a threesixtygiving domain name.

2022-03-24 15:57 UTC, BibianaC commented on src/components/02-elements/cookie-consent/cookie-consent.njk
> +          for(var i = 0; i < cookieArray.length; i++){
Thanks, @michaelwood. I have simplified it.

2022-03-24 15:57 UTC, BibianaC commented on src/components/02-elements/cookie-consent/cookie-consent.njk
> +          ["rememberCookieConsentGiven", "optUserOut", "noEnhancedAnalytics"].forEach(cookieExist);
Thanks

2022-03-25 15:32 UTC, merged